name: dotori_mobile
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_messaging: ^14.2.1
  firebase_crashlytics: ^3.0.11
  firebase_app_check: ^0.1.1+8
  firebase_dynamic_links: ^5.0.11
  http: ^0.13.5
  freezed_annotation: ^2.2.0
  provider: ^6.0.5
  json_annotation: ^4.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  csv: ^5.0.1
  get_it: ^7.2.0
  intl: ^0.18.0
  flutter_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.4.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/img/

  fonts:
    - family: NotoSans
      fonts:
        - asset: asset/font/NotoSansKR-Black.otf
          weight: 900
        - asset: asset/font/NotoSansKR-Bold.otf
          weight: 700
        - asset: asset/font/NotoSansKR-Light.otf
          weight: 500
        - asset: asset/font/NotoSansKR-Medium.otf
          weight: 400
        - asset: asset/font/NotoSansKR-Regular.otf
          weight: 300
        - asset: asset/font/NotoSansKR-Thin.otf
          weight: 100
