// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDujBzbqYTBT5JTB-B3I5wwx0uyGs4weI',
    appId: '1:55527379469:web:d9955a5a45177798b53b44',
    messagingSenderId: '55527379469',
    projectId: 'dotori-a42bb',
    authDomain: 'dotori-a42bb.firebaseapp.com',
    storageBucket: 'dotori-a42bb.appspot.com',
    measurementId: 'G-HTX105Z200',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTnC6cu7AVBooY7__bSGCR8VG9TWx0P0Y',
    appId: '1:55527379469:android:c45790344efbbde7b53b44',
    messagingSenderId: '55527379469',
    projectId: 'dotori-a42bb',
    storageBucket: 'dotori-a42bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf6HjG13MP5n6LZmRH3N3mWVJbrJDUO7Q',
    appId: '1:55527379469:ios:f1578e04ee8a9c84b53b44',
    messagingSenderId: '55527379469',
    projectId: 'dotori-a42bb',
    storageBucket: 'dotori-a42bb.appspot.com',
    iosClientId: '55527379469-kls6du6vtc6ls4vn0mm31gn6hd3vcqd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dotoriMobile',
  );
}
